apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgfdss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgfdss
  template:
    metadata:
      labels:
        app: dgfdss
    spec:
      containers:
      - image: okteto.dev/dgfdss:latest
        name: dgfdss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "146ea519-e97d-4784-b98a-fca1d03ccdd7"
        - name: Vless_Path
          value: "/146ea519-e97d-4784-b98a-fca1d03ccdd7-vless"
        - name: Vmess_UUID
          value: "146ea519-e97d-4784-b98a-fca1d03ccdd7"
        - name: Vmess_Path
          value: "/146ea519-e97d-4784-b98a-fca1d03ccdd7-vmess"
        - name: Share_Path
          value: "/v2oktink"
